# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js ${{ matrix.node-version }} and cache npm dependencies
      run: |
        node_version=${{ matrix.node-version }}
        cache_dir=".npm_cache"

        # Set up Node.js
        curl -fsSL https://deb.nodesource.com/setup_${node_version}.x | sudo -E bash -
        sudo apt-get install -y nodejs

        # Set up npm cache
        npm config set cache ${HOME}/${cache_dir}
        npm install -g npm@latest

        # Restore npm dependencies from cache or install if cache is not found
        npm ci

      env:
        cache_dir: .npm_cache
      working-directory: ./frontend
    - run: npm ci
      working-directory: ./frontend
    
    - run: npm run test:unit
      working-directory: ./frontend
    
